#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""voice-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google_Gemini (LLM)
- Deepgram (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.transports.base_transport import TransportParams
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from openrouter_cerebras_llm import OpenRouterCerebrasLLMService
from loguru import logger
from dotenv import load_dotenv
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.frames.frames import LLMRunFrame
from pipecat.services.deepgram.flux.stt import DeepgramFluxSTTService
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
import os
import aiohttp
from pipecat.pipeline.pipeline import Pipeline
from pipecat.runner.types import RunnerArguments
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.transports.base_transport import BaseTransport
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.pipeline.runner import PipelineRunner
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport

load_dotenv(override=True)

from rumik_tts import RumikTTSService, RumikTTSSettings


def build_system_prompt(counsellor: dict | None) -> str:
    if not counsellor:
        return (
            "You are a warm, friendly astrology counsellor speaking on a voice call. "
            "Keep replies short (1-3 sentences). Avoid emojis, lists, or formatting. "
            "Ask one clarifying question at a time."
        )
    name = counsellor.get("name", "the counsellor")
    specialties = ", ".join(counsellor.get("specialties", [])) or "astrology"
    languages = ", ".join(counsellor.get("languages", [])) or "English and Hindi"
    exp = counsellor.get("experienceYears", 5)
    return (
        f"You are {name}, an Indian astrology counsellor with {exp} years of experience. "
        f"You specialise in {specialties}. You speak {languages}. "
        "You are on a live voice call with a client who has come for guidance on a personal matter. "
        "Speak warmly and unhurriedly, like an experienced practitioner. "
        "Keep replies short (1-3 sentences) — this is a voice conversation, not an essay. "
        "Avoid emojis, lists, or any formatting that doesn't speak naturally. "
        "If the client asks for a reading, ask one focused clarifying question first "
        "(birth time, birth place, the specific worry) before launching in. "
        "Greet the client by introducing yourself by name."
    )


async def run_bot(transport: BaseTransport, counsellor: dict | None = None):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramFluxSTTService(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        settings=DeepgramFluxSTTService.Settings(
            model="flux-general-en",
        ),
    )

    # Shared aiohttp session for HTTP-based services
    aiohttp_session = aiohttp.ClientSession()

    # Text-to-Speech service
    tts = RumikTTSService(
        api_key=os.getenv("SILK_API_KEY"),
        aiohttp_session=aiohttp_session,
        base_url=os.getenv("SILK_BASE_URL", "https://silk-api.rumik.ai"),
        settings=RumikTTSSettings(
            model=os.getenv("SILK_MODEL", "muga"),
            tone=os.getenv("SILK_TONE", "neutral"),
            speaker=os.getenv("SILK_SPEAKER") or None,
            description=os.getenv("SILK_DESCRIPTION") or None,
        ),
    )


    # LLM service
    llm = OpenRouterCerebrasLLMService(
        api_key=os.getenv("OPENROUTER_API_KEY"),
        providers=[p.strip() for p in os.getenv("OPENROUTER_PROVIDER", "Cerebras").split(",") if p.strip()],
        settings=OpenRouterCerebrasLLMService.Settings(
            model=os.getenv("OPENROUTER_MODEL", "z-ai/glm-4.7"),
        ),
    )



    context = LLMContext()
    context.add_message({"role": "system", "content": build_system_prompt(counsellor)})
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.4)),    ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
        ],
    )

    # Trigger the intro on the transport-level connected event so we don't
    # depend on the WebRTC data channel / RTVI handshake — the audio media
    # track is up by this point, which is all we need to play TTS.
    intro_sent = False

    async def send_intro():
        nonlocal intro_sent
        if intro_sent:
            return
        intro_sent = True
        intro = (
            f"Greet the client warmly as {counsellor.get('name')} and ask how you can help them today."
            if counsellor else "Please introduce yourself."
        )
        context.add_message({"role": "user", "content": intro})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected — sending intro")
        await send_intro()

    # Belt-and-braces: also fire on RTVI ready if the data channel does open.
    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        logger.info("RTVI client ready")
        await send_intro()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    try:
        await runner.run(task)
    finally:
        await aiohttp_session.close()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    counsellor = None
    body = getattr(runner_args, "body", None)
    logger.info(f"runner_args.body = {body!r}")
    if isinstance(body, dict):
        # The Pipecat JS SDK wraps user requestData inside an outer object that
        # also contains sdp/type/pc_id. Sometimes the server unwraps to just the
        # user data, sometimes not. Try both.
        counsellor = body.get("counsellor") or (
            body.get("requestData", {}).get("counsellor") if isinstance(body.get("requestData"), dict) else None
        ) or (
            body.get("request_data", {}).get("counsellor") if isinstance(body.get("request_data"), dict) else None
        )
    logger.info(f"resolved counsellor = {counsellor}")

    await run_bot(transport, counsellor=counsellor)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()