#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""voice-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google_Gemini (LLM)
- Deepgram (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.transports.base_transport import TransportParams
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.services.google.llm import GoogleLLMService
from loguru import logger
from dotenv import load_dotenv
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.frames.frames import LLMRunFrame
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
import os
import aiohttp
from pipecat.pipeline.pipeline import Pipeline
from pipecat.runner.types import RunnerArguments
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.transports.base_transport import BaseTransport
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.pipeline.runner import PipelineRunner
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport

load_dotenv(override=True)

from rumik_tts import RumikTTSService, RumikTTSSettings


def build_system_prompt(counsellor: dict | None) -> str:
    if not counsellor:
        return (
            "You are a warm, friendly astrology counsellor speaking on a voice call. "
            "Keep replies short (1-3 sentences). Avoid emojis, lists, or formatting. "
            "Ask one clarifying question at a time."
        )
    name = counsellor.get("name", "the counsellor")
    specialties = ", ".join(counsellor.get("specialties", [])) or "astrology"
    languages = ", ".join(counsellor.get("languages", [])) or "English and Hindi"
    exp = counsellor.get("experienceYears", 5)
    return (
        f"You are {name}, an Indian astrology counsellor with {exp} years of experience. "
        f"You specialise in {specialties}. You speak {languages}. "
        "You are on a live voice call with a client who has come for guidance on a personal matter. "
        "Speak warmly and unhurriedly, like an experienced practitioner. "
        "Keep replies short (1-3 sentences) — this is a voice conversation, not an essay. "
        "Avoid emojis, lists, or any formatting that doesn't speak naturally. "
        "If the client asks for a reading, ask one focused clarifying question first "
        "(birth time, birth place, the specific worry) before launching in. "
        "Greet the client by introducing yourself by name."
    )


async def run_bot(transport: BaseTransport, counsellor: dict | None = None):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    # Shared aiohttp session for HTTP-based services
    aiohttp_session = aiohttp.ClientSession()

    # Text-to-Speech service
    tts = RumikTTSService(
        api_key=os.getenv("SILK_API_KEY"),
        aiohttp_session=aiohttp_session,
        base_url=os.getenv("SILK_BASE_URL", "https://silk-api.rumik.ai"),
        settings=RumikTTSSettings(
            model=os.getenv("SILK_MODEL", "mulberry"),
            speaker=os.getenv("SILK_SPEAKER", "speaker_1"),
            description=(
                "Warm, calm, experienced Indian astrologer voice. "
                "Mid-paced delivery suitable for a counselling phone call."
            ),
        ),
    )


    # LLM service
    llm = GoogleLLMService(
        api_key=os.getenv("GOOGLE_API_KEY"),
        settings=GoogleLLMService.Settings(
            model=os.getenv("GOOGLE_MODEL", "gemini-flash-latest"),
            system_instruction=build_system_prompt(counsellor),
        ),
    )



    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),    ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
        ],
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        intro = (
            f"Greet the client warmly as {counsellor.get('name')} and ask how you can help them today."
            if counsellor else "Please introduce yourself."
        )
        context.add_message({"role": "user", "content": intro})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    try:
        await runner.run(task)
    finally:
        await aiohttp_session.close()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    counsellor = None
    body = getattr(runner_args, "body", None)
    if isinstance(body, dict):
        counsellor = body.get("counsellor")

    await run_bot(transport, counsellor=counsellor)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()